"""Implement sitemap versioning: remove unique constraint, add is_active

Revision ID: d64ca6737642
Revises: 4df5dab2a3ab
Create Date: 2025-04-04 18:00:39.481309

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd64ca6737642'
down_revision: Union[str, None] = '4df5dab2a3ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sitemap', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.drop_constraint('sitemap_project_id_key', 'sitemap', type_='unique')
    op.create_index(op.f('ix_sitemap_is_active'), 'sitemap', ['is_active'], unique=False)
    op.create_index('ix_sitemap_project_id_is_active', 'sitemap', ['project_id', 'is_active'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_sitemap_project_id_is_active', table_name='sitemap')
    op.drop_index(op.f('ix_sitemap_is_active'), table_name='sitemap')
    op.create_unique_constraint('sitemap_project_id_key', 'sitemap', ['project_id'])
    op.drop_column('sitemap', 'is_active')
    # ### end Alembic commands ###
